### ISSUE TITLE
No module named 'sparsemul'

### ISSUE THREAD

**Issue by zhanghui186** [hbhargava7/cryoem-data-simulation#1]
Sorry for bothering you, I can not find a model named sparsemul.

**Comment by hbhargava7** [comment]
Where are you seeing this error? Perhaps you need to add `cryoem-cython-pyx/sparesemul` to your path?

**Comment by zhanghui186** [comment]
terribly sorry, I didn't read your tutorial carefully before, and now the problem is solved, thank you, your code is very helpful to me!
